spring.application.name=file-service
server.port=8088

# Cloudinary
cloudinary.cloud-name=dh0ypvr7a
cloudinary.api-key=524837922971933
cloudinary.api-secret=3CYOitaFT6lynA1TtQIo_f3Q3Sc

# Allow large file uploads (PDFs, etc.)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB